MAX_WEAR_CONDITION = 100
WEAR_STEP = 10
HUNDRED = 100
PERCENT_MAXIMUM_DAMAGE = 40
CRITICAL_DAMAGE_PERCENT = 15
PERCENT_MAGNETIC_STORM = 20
MAX_SPACESHIP_HEALTH = 1000

EQUIPMENT_TYPES = ('защитного', 'атакующего', 'навигационного')
